# Generated by Django 4.1.6 on 2023-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripeAPI", "0002_order_item_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
