# Generated by Django 4.1.6 on 2023-02-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stripeAPI", "0003_item_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stripeAPI.order",
            ),
        ),
    ]
