# Generated by Django 4.1.6 on 2023-02-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripeAPI", "0005_item_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("USD", "usd"), ("EUR", "eur")], default="usd", max_length=3
            ),
        ),
    ]
