# Generated by Django 4.1.6 on 2023-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripeAPI", "0006_alter_item_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "usd"), ("EUR", "eur")],
                        default="usd",
                        max_length=3,
                    ),
                ),
                ("price", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="item",
            name="currency",
        ),
        migrations.AddField(
            model_name="item",
            name="currencies",
            field=models.ManyToManyField(to="stripeAPI.itemcurrency"),
        ),
    ]
