# Generated by Django 4.1.6 on 2023-02-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "stripeAPI",
            "0008_currency_remove_item_currencies_itemcurrency_item_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.AlterField(
            model_name="item",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stripeAPI.order",
            ),
        ),
    ]
